version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    backend:
        build: 
            context: .
            dockerfile: Dockerfile.backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/app
        depends_on:
            - db
        ports:
            - "8000:8000"

    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.frontend
        command: npm start
        volumes:
            - ./frontend:/app/frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
